Create tmhmm.py
Deep TMHMM (takes a long time)
WORKS: needed to be upgraded

biolib run DTU/DeepTMHMM --fasta file.fa


Error: python script tmhmm.py

    Image(filename=png_out)
  File "/home/sareh/.local/lib/python3.6/site-packages/IPython/core/display.py", line 1216, in __init__
    raise ValueError("Cannot embed the '%s' image format" % (self.format))
ValueError: Cannot embed the '1' image format